theme: minima
title: Speaking my mind out!
author: yeshu
email: mammufun@outlook.com
description: > # this means to ignore newlines until "baseurl:"
 Harry Potter is awesome! (Don't mind the present trans row with JKR though :)) 
 PJO and HoO are cool too, 
 and if you have a thing with humour grab them as they are overloades with extra sass and puns everywhere.

# social links
facebook_username: yeshwanth 
github_username:  yesh-wanth # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
